name: Docker Build and Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: "product" # Nếu bạn dùng environment secrets

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          # Build and push Docker images using buildx
          cd ./eureka-server && docker buildx build --platform linux/amd64 --push -t ${{ secrets.DOCKER_USERNAME }}/eureka-server:latest .
          cd ../gateway-service && docker buildx build --platform linux/amd64 --push -t ${{ secrets.DOCKER_USERNAME }}/gateway-service:latest .
          cd ../user-service && docker buildx build --platform linux/amd64 --push -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest .
          cd ../product-service && docker buildx build --platform linux/amd64 --push -t ${{ secrets.DOCKER_USERNAME }}/product-service:latest .
          cd ../order-service && docker buildx build --platform linux/amd64 --push -t ${{ secrets.DOCKER_USERNAME }}/order-service:latest .
          cd ../inventory-service && docker buildx build --platform linux/amd64 --push -t ${{ secrets.DOCKER_USERNAME }}/inventory-service:latest .
          cd ../payment-service && docker buildx build --platform linux/amd64 --push -t ${{ secrets.DOCKER_USERNAME }}/payment-service:latest .
          cd ../ai-chat-service && docker buildx build --platform linux/amd64 --push -t ${{ secrets.DOCKER_USERNAME }}/ai-chat-service:latest .

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /path/to/deployment
            git pull

            # Pull latest images from Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/eureka-server:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/gateway-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/user-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/product-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/order-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/inventory-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/payment-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/ai-chat-service:latest

            # Restart all services
            docker-compose down
            docker-compose up -d
