name: Docker Build and Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: "product"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Kiểm tra cấu trúc thư mục sau khi checkout
        run: |
          ls -la
          find . -type f
          echo "Kiểm tra Dockerfile trong eureka-server"
          ls -la eureka-server
          cat eureka-server/Dockerfile

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build Maven projects
        run: |
          mvn clean package -DskipTests
          echo "Kiểm tra tệp JAR trong eureka-server"
          ls -la eureka-server/target || echo "Thư mục target không tồn tại"

      - name: Kiểm tra DOCKER_USERNAME
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "Lỗi: DOCKER_USERNAME không được thiết lập"
            exit 1
          fi
          # Kiểm tra ký tự không hợp lệ
          echo "Kiểm tra DOCKER_USERNAME có ký tự xuống dòng hoặc khoảng trắng"
          echo "${{ secrets.DOCKER_USERNAME }}" | od -c

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Kiểm tra thông tin Docker
        run: |
          docker info
          docker version
          docker buildx version
          docker buildx ls

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for eureka-server
        run: |
          echo "Xây dựng eureka-server"
          echo "Lệnh: docker buildx build --platform linux/amd64 --push -t ${{ secrets.DOCKER_USERNAME }}/eureka-server:latest ./eureka-server"
          docker buildx build --platform linux/amd64 --push -t ${{ secrets.DOCKER_USERNAME }}/eureka-server:latest ./eureka-server
          if [ $? -ne 0 ]; then
            echo "Lỗi khi build eureka-server, thử build không push"
            docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/eureka-server:latest ./eureka-server
          fi

      - name: Build and push other Docker images
        run: |
          echo "Xây dựng các dịch vụ khác"
          for service in gateway-service user-service product-service order-service inventory-service payment-service ai-chat-service; do
            echo "Xây dựng $service"
            echo "Lệnh: docker buildx build --platform linux/amd64 --push -t ${{ secrets.DOCKER_USERNAME }}/$service:latest ./$service"
            docker buildx build --platform linux/amd64 --push -t ${{ secrets.DOCKER_USERNAME }}/$service:latest ./$service
            if [ $? -ne 0 ]; then
              echo "Lỗi khi build $service"
              exit 1
            fi
          done

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /path/to/deployment
            git pull
            docker pull ${{ secrets.DOCKER_USERNAME }}/eureka-server:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/gateway-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/user-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/product-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/order-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/inventory-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/payment-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/ai-chat-service:latest
            docker-compose down
            docker-compose up -d
