name: Docker CI/CD for Microservices

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Images (No Push for PR)
    runs-on: ubuntu-latest
    environment: "product"
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image for user-service (example)
        run: |
          docker build ./user-service --file ./user-service/Dockerfile --tag user-service:test

  build-and-deploy:
    name: Build & Push All Microservices
    runs-on: ubuntu-latest
    environment: "product"
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          services=(
            "eureka-server"
            "gateway-service"
            "user-service"
            "product-service"
            "order-service"
            "inventory-service"
            "payment-service"
            "ai-chat-service"
          )
          for service in "${services[@]}"; do
            echo "Building and pushing $service"
            docker build -t ${{ secrets.DOCKER_USERNAME }}/$service:latest ./$service
            docker push ${{ secrets.DOCKER_USERNAME }}/$service:latest
          done

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /path/to/deployment
            git pull
            services=(
              "eureka-server"
              "gateway-service"
              "user-service"
              "product-service"
              "order-service"
              "inventory-service"
              "payment-service"
              "ai-chat-service"
            )
            for service in "${services[@]}"; do
              docker pull ${{ secrets.DOCKER_USERNAME }}/$service:latest
            done
            docker-compose down
            docker-compose up -d
