name: Docker Build and Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: "product"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Kiểm tra cấu trúc thư mục sau khi checkout
        run: |
          pwd
          ls -la
          find . -type f

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          cd BE/BE
          for service in eureka-server gateway-service user-service product-service order-service inventory-service payment-service ai-chat-service; do
            if [ -d "$service" ]; then
              echo "✅ Building $service..."
              docker buildx build \
                --platform linux/amd64 \
                --push \
                -t ${{ secrets.DOCKER_USERNAME }}/$service:latest \
                ./$service
            else
              echo "❌ Skipping $service: directory not found"
            fi
          done

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /path/to/deployment
            git pull

            docker pull ${{ secrets.DOCKER_USERNAME }}/eureka-server:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/gateway-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/user-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/product-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/order-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/inventory-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/payment-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/ai-chat-service:latest

            docker-compose down
            docker-compose up -d
