name: Docker Build and Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: "product"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag microservice images
        run: |
          # Build Docker images for each microservice
          docker build -t ${{ secrets.DOCKER_USERNAME }}/eureka-server:latest ./eureka-server
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gateway-service:latest ./gateway-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest ./user-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/product-service:latest ./product-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/order-service:latest ./order-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/inventory-service:latest ./inventory-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/payment-service:latest ./payment-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ai-chat-service:latest ./ai-chat-service

      - name: Push Docker images
        run: |
          # Push images to Docker Hub
          docker push ${{ secrets.DOCKER_USERNAME }}/eureka-server:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/gateway-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/product-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/order-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/inventory-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/payment-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ai-chat-service:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /path/to/deployment
            git pull

            # Pull latest images
            docker pull ${{ secrets.DOCKER_USERNAME }}/eureka-server:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/gateway-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/user-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/product-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/order-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/inventory-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/payment-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/ai-chat-service:latest

            # Update docker-compose.yml if needed and restart services
            docker-compose down
            docker-compose up -d
