name: Docker Build and Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: "product"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push images for all services
        uses: actions/github-script@v6
        with:
          script: |
            const services = [
              "eureka-server",
              "gateway-service",
              "user-service",
              "product-service",
              "order-service",
              "inventory-service",
              "payment-service",
              "ai-chat-service"
            ];
            for (const service of services) {
              core.startGroup(`🔨 Building ${service}`);
              await exec.exec('docker', [
                'buildx', 'build',
                '--builder', process.env.BUILDX_BUILDER_NAME,
                '--push',
                '--platform', 'linux/amd64',
                '--tag', `${process.env.DOCKER_USERNAME}/${service}:latest`,
                service // context = ./service
              ]);
              core.endGroup();
            }

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /path/to/deployment
            git pull
            docker pull ${{ secrets.DOCKER_USERNAME }}/eureka-server:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/gateway-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/user-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/product-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/order-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/inventory-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/payment-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/ai-chat-service:latest
            docker-compose down
            docker-compose up -d
